-- Supabase setup for Lights, Camera, Business
-- Run this in your Supabase SQL Editor

-- Create profiles table (linked to auth.users)
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  name text,
  tier text default 'starter' check (tier in ('starter', 'indie', 'pro')),
  created_at timestamptz default now()
);

-- Create projects table
create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  type text not null,
  data jsonb default '{}',
  created_at timestamptz default now()
);

-- Enable RLS
alter table public.profiles enable row level security;
alter table public.projects enable row level security;

-- Profiles policies
create policy "Users can view own profile" on public.profiles
  for select using (auth.uid() = id);

create policy "Users can update own profile" on public.profiles
  for update using (auth.uid() = id);

create policy "Users can insert own profile" on public.profiles
  for insert with check (auth.uid() = id);

-- Projects policies
create policy "Users can view own projects" on public.projects
  for select using (auth.uid() = user_id);

create policy "Users can insert own projects" on public.projects
  for insert with check (auth.uid() = user_id);

create policy "Users can update own projects" on public.projects
  for update using (auth.uid() = user_id);

create policy "Users can delete own projects" on public.projects
  for delete using (auth.uid() = user_id);

-- Create trigger to auto-create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, name)
  values (new.id, new.raw_user_meta_data->>'name');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
